# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:49:37+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import GetfullnamematchGetResponse

app = MCPProxy(
    contact={
        'email': 'support@interzoid.com',
        'name': 'API Support',
        'url': 'https://www.interzoid.com',
        'x-twitter': 'interzoid',
    },
    description='This API provides a similarity key used to match with other similar full name data, including for purposes of deduplication, fuzzy matching, or merging of datasets. A much higher match rate will be achieved by matching on the similarity key rather than the data itself. This API is for full name data where first and last name are in the same field. Use the Full Name Parsed Similarity Key API for first and last name data that are in separate fields.',
    license={'name': 'Interzoid license', 'url': 'https://www.interzoid.com/license'},
    termsOfService='https://www.interzoid.com/terms',
    title='Interzoid Get Full Name Match Similarity Key API',
    version='1.0.0',
    servers=[{'url': 'https://api.interzoid.com'}],
)


@app.get(
    '/getfullnamematch',
    description=""" Gets a similarity key for matching purposes for full name data, where first and last name are part of the same field. """,
    tags=['name_matching_operations'],
)
def getfullnamematch(license: str, fullname: str = ...):
    """
    Gets a similarity key for matching purposes for full name data
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
