# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:49:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetfullnamematchGetResponse(BaseModel):
    Code: Optional[str] = None
    Credits: Optional[str] = None
    Simkey: Optional[str] = None
